[project]
name = "mass-lighting"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "micropython-esp32-stubs>=1.27.0.post1",
    "micropython-stdlib-stubs>=1.27.0.post1",
]
